server: 
  port: 3344
spring:
  application:
    name:  microservice-config
  cloud:
    config:
      server:
        git:
           uri: https://github.com/mrlsongzz/microservicecloud-config.git #GitHub上面的git仓库名字
          #uri: git@github.com:1156598192/microservicecloud-config.git  会访问不到数据要注意
 

