server:
  port: 7001

eureka:
  instance:
    hostname:localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
          #单机 defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/       #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
          defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/



